services:
  spot_back:
    build: .
    ports:
      -  "1234: 1234"

    restart: unless-stopped

    env_file:
      - .env
    environment:
      - INTERACTION_MODE=drawing
    privileged: true
    volumes:
      - "./traces:${TRACES_DIR}"
      - "./logs:/logs"
      - "./calibrations:${CALIBRATIONS_DIR}"
volumes:
  prometheus_data: {}
