services:
  spot_back:
    build: .
    network_mode:
      host

    restart: unless-stopped

    env_file:
      - .env
    environment:
      - INTERACTION_MODE=drawing
    privileged: true
    volumes:
      - ./traces:/home/spot/spot.merklebot.com/spot/traces
      - ./calibrations:/home/spot/spot.merklebot.com/spot/calibrations

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - "$PWD/services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    network_mode: host
    ports:
      - "127.0.0.1:9090:9090"
