services:
  spot_back:
    build: .
    network_mode:
      host

    restart: unless-stopped

    env_file:
      - .env
    environment:
      - INTERACTION_MODE=drawing
    privileged: true
    volumes:
      - "./traces:${TRACES_DIR}"
      - "./logs:/logs"
      - "./calibrations:${CALIBRATIONS_DIR}"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - "$PWD/services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.listen-address=:9010'
    network_mode: host
    ports:
      - "127.0.0.1:9010:9010"

  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: datadog-agent
    network_mode: host
    ports:
      - 8126:8126
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      -  /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      DD_API_KEY: ${DATADOG_API_KEY}
      DD_SITE: ${DATADOG_SITE}
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: true

volumes:
  prometheus_data: {}
