services:
  videoserver:
    build: .
    ports:
      - "8000:8000"

    restart: unless-stopped
    
    env_file:
      - .env
    environment:
      - SPOT_MOVING=
    privileged: true
    devices:
      - '/dev:/dev'
    logging:
      driver: "json-file"
      options:
        max-size: "30m"

